[package]
name = "maeel_interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maeel_common = { path = "../maeel_common" }
maeel_lexer = { path = "../maeel_lexer" }
