condense_wildcard_suffixes = true
reorder_imports = false
combine_control_expr = false
reorder_modules = false
empty_item_single_line = false
match_arm_leading_pipes = "Never"
brace_style = "AlwaysNextLine"
struct_field_align_threshold = 30
enum_discrim_align_threshold = 30
force_multiline_blocks = true
format_macro_matchers = true
imports_layout = "Vertical"
struct_lit_single_line = false
use_field_init_shorthand = true
match_arm_blocks = true
format_strings = true
trailing_semicolon = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
chain_width = 30
max_width = 70
reorder_impl_items = true
